### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by Cyorageeee** [Kristall-WangShiwei/Transgender-lost-years#26]
以把你的性别认同列表转载到我的网站吗？我会注明原作者。
我的网站：Cyorageeee.github.io

**Comment by b1f6c1c4** [comment]
https://github.com/Kristall-WangShiwei/Transgender-lost-years/blob/master/LICENSE

**Comment by KristallWang** [comment]
把我们这些二次整合作者，二次整合的链接，第一次整理的链接，第一次整理的原作者都注明（

**Comment by Cyorageeee** [comment]
> 把我们这些二次整合作者，二次整合的链接，第一次整理的链接，第一次整理的原作者都注明（

好的。谢谢你。我希望这能帮到更多的人。
