### ISSUE TITLE
README 最下面的友链证书错误

### ISSUE THREAD

**Issue by Master-Hash** [Kristall-WangShiwei/Transgender-lost-years#34]
我试着忽视浏览器的警告访问该网址，最终跳转到了一个[新的域名](https://www.transonline.org.cn/)，看内容新域名应该没问题，也不存在证书错误。  
~~话说那个坑打算什么时候填~~

**Comment by Master-Hash** [comment]
@Kristall-WangShiwei

**Comment by KristallWang** [comment]
呃…那锅我不背…得找站长去…

**Comment by Master-Hash** [comment]
我的意思是，链接被重定向了，原网址的证书无效，目标网址证书有效。所以请你把网址改成目标网址
