### ISSUE TITLE
北医三院胡佩诚可开具证明

### ISSUE THREAD

**Issue by MzeroMiko** [Kristall-WangShiwei/Transgender-lost-years#52]
我是2020年在北医三院胡佩诚处开具的证明，明确写有“诊断：易性证”类似字样。胡佩诚处需观察一年，也就是一年后第二次就诊才会开具证明

**Comment by KristallWang** [comment]
需要介绍信的大证明还是…？

**Comment by MzeroMiko** [comment]
并不是直接用于手术的单子，而是国内手术四大件(父母知情同意书+个人意愿书+无犯罪记录+易性症证明) 中的易性症证明那项。利用该证明可以找潘医生开药，如果集齐前三项(有的医院还需要精神状态良好)，就可以在国内手术。



---原始邮件---
发件人: "Kristall ***@***.***&gt;
发送时间: 2021年3月12日(周五) 下午2:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [KristallWang/Transgender-lost-years] 北医三院胡佩诚可开具证明 (#52)




 
需要介绍信的大证明还是…？
