### ISSUE TITLE
鉴于 GitHub 已经在境内多地被 GFW 阻断/劣化连接的现状，建议利用 Gitee/Coding 等境内平台同步镜像 repo。

### ISSUE THREAD

**Issue by 255doesnotexist** [Kristall-WangShiwei/Transgender-lost-years#60]
![Github.com 多地测速](https://z3.ax1x.com/2021/07/04/Rf4FQP.png)

- 关于如何同步：
- [https://gyx8899.gitbook.io/blog/share/syncgithubtogitee](https://gyx8899.gitbook.io/blog/share/syncgithubtogitee)

**Comment by nexplorer-3e** [comment]
bitbucket, gitlab 也行吧
gitee 是不是有个同步前登录😶

**Comment by cyjin-yl** [comment]
> bitbucket, gitlab 也行吧
> gitee 是不是有个同步前登录😶

都行吧。反正某群里有人问给了这里的链接结果人家没梯子打不开就很尴尬了。
